filter:
    excluded_paths:
        - tests/*
        - node_modules/
        - coverage
        - build
build:
    nodes:
        analysis:
            tests:
                override:
                    - eslint-run "./src"
                    - js-scrutinizer-run
                    - npm test
