build:
  nodes:
    coverage:
      tests:
        override:
          - command: npm run test
            coverage:
              file: coverage/clovertest.xml   # <- Set this to where we find the coverage data.
                                          #    The path is relative to the current directory.
              format: clover
