build:
    nodes:
        analysis:
            tests:
                override:
                    - eslint-run "./src"
                    - js-scrutinizer-run
                    - npm test
